package Problems;

/**
 * Created by Arnold on 11-9-2017.
 */
public class Problem2 extends Functions {

    //Each new term in the Fibonacci sequence is generated by adding the previous two
    //terms. By starting with 1 and 2, the first 10 terms will be:
    //          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed
    //four million, find the sum of the even-valued terms.

    private int max = 4000000;
    private int sum = 0;

    private int firstStartingNumber = 1;
    private int secondStartingNumber = 2;
    private int term;

    private int answer = 0;

    public Problem2(){

        //Initialize the variables
        sum = secondStartingNumber;
        term = firstStartingNumber;
        int x;
        int i;

        //Initialize the loop
        do{

            i=sum;
            sum+=term;
            if(term%2==0){
                answer+=term;
            }
            term = i;

        } while(term<max);

        //Print solution
        print(answer);

    }

}
